# Computer Science Basics
Because even after doing algorithm trading, physics, and earning an MSc in engineering you still have to prove you can sort a list.

We'll go in order of speed from slowest to fasted:  
1 Sorting  
1.1 Bubble sort  
1.2 Insertion sort  
1.3 Selection sort  
1.4 Quick sort  
1.5 Merge sort  
2 Searching  
2.1 Linear Search  
2.2 Jump Search  
2.3 Binary Search  

## 1 Sorting
### 1.1 Bubble Sort
<pre>
Best case: O(n) comparisons  
           O(1) swaps  
Average case: O(n^2) comparisons  
              O(n^2) swaps  
Worst case: O(n^2) comparisons  
            O(n^2) swaps  
</pre>

In [1]:
import numpy as np
import random

A = np.arange(1, 11)
random.shuffle(A)
print('List 1-10 in Shuffled:')
print(A)
print('\nThe process...')

def bubbleSort(A):
    n = len(A)
    if(n == 0):
        return 'The list is empty'
    swaps = 1
    while swaps > 0:
        swaps = 0
        for i in range(1, len(A)):
            if(A[i-1] > A[i]):
                A[i-1], A[i] = A[i], A[i-1]
                swaps += 1
                print(A)
    return(A)
                
A = bubbleSort(A)
print('\nSorted by Bubble Sort:')
print(A)

List 1-10 in Shuffled:
[ 7  4  2  8  5  3 10  9  1  6]

The process...
[ 4  7  2  8  5  3 10  9  1  6]
[ 4  2  7  8  5  3 10  9  1  6]
[ 4  2  7  5  8  3 10  9  1  6]
[ 4  2  7  5  3  8 10  9  1  6]
[ 4  2  7  5  3  8  9 10  1  6]
[ 4  2  7  5  3  8  9  1 10  6]
[ 4  2  7  5  3  8  9  1  6 10]
[ 2  4  7  5  3  8  9  1  6 10]
[ 2  4  5  7  3  8  9  1  6 10]
[ 2  4  5  3  7  8  9  1  6 10]
[ 2  4  5  3  7  8  1  9  6 10]
[ 2  4  5  3  7  8  1  6  9 10]
[ 2  4  3  5  7  8  1  6  9 10]
[ 2  4  3  5  7  1  8  6  9 10]
[ 2  4  3  5  7  1  6  8  9 10]
[ 2  3  4  5  7  1  6  8  9 10]
[ 2  3  4  5  1  7  6  8  9 10]
[ 2  3  4  5  1  6  7  8  9 10]
[ 2  3  4  1  5  6  7  8  9 10]
[ 2  3  1  4  5  6  7  8  9 10]
[ 2  1  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]

Sorted by Bubble Sort:
[ 1  2  3  4  5  6  7  8  9 10]


### 1.2 Insertion Sort
<pre>
Best case: O(n) comparisons  
           O(1) swaps  
Average case: O(n^2) comparisons  
              O(n^2) swaps  
Worst case: O(n^2) comparisons  
            O(n^2) swaps  
</pre>

In [2]:
A = np.arange(1, 11)
random.shuffle(A)
print('List 1-10 in Shuffled:')
print(A)
print('\nThe process...')

def insertionSort(A):
    n = len(A)
    if(n == 0):
        return 'The list is empty'
    i = 1
    while i < n:
        j = i
        while j > 0 and A[j-1] > A[j]:
            A[j-1], A[j] = A[j], A[j-1]
            j -= 1
            print(A)
        i += 1
    return A  

A = insertionSort(A)
print('\nSorted by Insertion Sort:')
print(A)

List 1-10 in Shuffled:
[10  8  2  7  9  6  4  1  5  3]

The process...
[ 8 10  2  7  9  6  4  1  5  3]
[ 8  2 10  7  9  6  4  1  5  3]
[ 2  8 10  7  9  6  4  1  5  3]
[ 2  8  7 10  9  6  4  1  5  3]
[ 2  7  8 10  9  6  4  1  5  3]
[ 2  7  8  9 10  6  4  1  5  3]
[ 2  7  8  9  6 10  4  1  5  3]
[ 2  7  8  6  9 10  4  1  5  3]
[ 2  7  6  8  9 10  4  1  5  3]
[ 2  6  7  8  9 10  4  1  5  3]
[ 2  6  7  8  9  4 10  1  5  3]
[ 2  6  7  8  4  9 10  1  5  3]
[ 2  6  7  4  8  9 10  1  5  3]
[ 2  6  4  7  8  9 10  1  5  3]
[ 2  4  6  7  8  9 10  1  5  3]
[ 2  4  6  7  8  9  1 10  5  3]
[ 2  4  6  7  8  1  9 10  5  3]
[ 2  4  6  7  1  8  9 10  5  3]
[ 2  4  6  1  7  8  9 10  5  3]
[ 2  4  1  6  7  8  9 10  5  3]
[ 2  1  4  6  7  8  9 10  5  3]
[ 1  2  4  6  7  8  9 10  5  3]
[ 1  2  4  6  7  8  9  5 10  3]
[ 1  2  4  6  7  8  5  9 10  3]
[ 1  2  4  6  7  5  8  9 10  3]
[ 1  2  4  6  5  7  8  9 10  3]
[ 1  2  4  5  6  7  8  9 10  3]
[ 1  2  4  5  6  7  8  9  3 10]
[ 1  2  4  5  6  7  8  3  9 10]
[

### 1.3 Selection Sort
<pre>
Best case: O(n^2) comparisons  
           O(n) swaps  
Average case: O(n^2) comparisons  
              O(n) swaps  
Worst case: O(n^2) comparisons  
            O(n) swaps  
</pre>

In [3]:
A = np.arange(1, 11)
random.shuffle(A)
print('List 1-10 in Shuffled:')
print(A)
print('\nThe process...')

def selectionSort(A):
    n = len(A)
    A = list(A)
    if(n == 0):
        return 'The list is empty'

    for i in range(0, n):
        minA = A[i]
        item = i
        for j in range(i+1, n):
            if(A[j] < minA):
                minA = A[j]
                item = j
        A[i], A[item] = A[item], A[i]
        print(A)
        
    return A

A = selectionSort(A)
print('\nSorted by Selection Sort:')
print(A)

List 1-10 in Shuffled:
[ 6  4  3  1  7  9  5 10  2  8]

The process...
[1, 4, 3, 6, 7, 9, 5, 10, 2, 8]
[1, 2, 3, 6, 7, 9, 5, 10, 4, 8]
[1, 2, 3, 6, 7, 9, 5, 10, 4, 8]
[1, 2, 3, 4, 7, 9, 5, 10, 6, 8]
[1, 2, 3, 4, 5, 9, 7, 10, 6, 8]
[1, 2, 3, 4, 5, 6, 7, 10, 9, 8]
[1, 2, 3, 4, 5, 6, 7, 10, 9, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Sorted by Selection Sort:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


###  1.4 Quick Sort
<pre>
Best case: O(n log(n))  
Average case: O(n log(n))  
Worst case: O(n^2)   
</pre>

In [4]:
A = np.arange(1, 11)
random.shuffle(A)
print('List 1-10 in Shuffled:')
print(A)
print('\nThe process...')

def quickSort(A, low, high):
    if(len(A) == 0):
        return 'The list is empty'
    if(low < high):
        pivotvalue = partition(A, low, high)
#         print(A[low, pivotvalue-1], A[pivotvalue+1, high])
        quickSort(A, low, pivotvalue-1)
        quickSort(A, pivotvalue+1, high)
        
    return A

def partition(A, low, high):
    print(A[low:high])
    pivotvalue = A[high]
    lo, hi = low, high - 1

    while(lo < high):
        while(lo <= hi and A[lo] <= pivotvalue):
            lo = lo + 1
        while(A[hi] >= pivotvalue and hi >= lo):
            hi = hi -1

        if lo > hi:
            break
        else:
            A[lo], A[hi] = A[hi], A[lo]

    A[lo], A[high] = A[high], A[lo]
    return lo

high = len(A)-1
A = quickSort(A, 0, high)
print('\nSorted by Quick Sort:')
print(A)

List 1-10 in Shuffled:
[10  7  2  1  5  9  4  8  6  3]

The process...
[10  7  2  1  5  9  4  8  6]
[1]
[10  5  9  4  8  6]
[6 5]
[5]
[ 8 10]

Sorted by Quick Sort:
[ 1  2  3  4  5  6  7  8  9 10]


### 1.5 Merge Sort 
<pre>
Best case: O(n log(n))  
Average case: O(n log(n))  
Worst case: O(n^2)   
</pre>

In [5]:
A = np.arange(1, 11)
random.shuffle(A)
print('List 1-10 in Shuffled:')
print(A)
print('\nThe process...')

def mergeSort(A):
    A = list(A)
    if(len(A) < 2):
        return A
    elif(len(A) == 0):
        return 'The list is empty'
        
    else:
        leftA, rightA = split(A)
        
    return merge(mergeSort(leftA), mergeSort(rightA))
        
def merge(leftA, rightA):
    if(len(leftA) == 0):
        return leftA
    elif(len(rightA) == 0):
        return rightA
    
    left, right = 0, 0
    merged = []
    n = len(leftA) + len(rightA)
    while(len(merged) < n):
        if(leftA[left] <= rightA[right]):
            merged.append(leftA[left])
            left += 1
        else:
            merged.append(rightA[right])
            right += 1
            
        if(right == len(rightA)):
                merged += leftA[left:]
                break
        elif(left == len(leftA)):
                merged += rightA[right:]
                break
    print(merged)
    return merged
    
def split(A):
    middle = int(len(A)/2)
    return A[:middle], A[middle:]

A = mergeSort(A)
print('\nSorted by Merge Sort:')
print(A)

List 1-10 in Shuffled:
[ 6  8  1  2  9  4  5  3 10  7]

The process...
[6, 8]
[2, 9]
[1, 2, 9]
[1, 2, 6, 8, 9]
[4, 5]
[7, 10]
[3, 7, 10]
[3, 4, 5, 7, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Sorted by Merge Sort:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## 2 Searching
Now that we've sorted things in lists, let's search for things in lists
### 2.1 Linear Search
<pre>
Best case: O(1)  
Average case: O(n)  
Worst case: O(n)   
</pre>

In [6]:
A = np.arange(0, 21, 2)
print('List A:')
print(A)
x = random.randint(0, 20)
print('Find: {}'.format(x))


def linearSearch(A, x):
    if(len(A) == 0):
        return 'The list is empty'
    for i in range(0, len(A)):
        if(A[i] == x):
            return 'Found {} in list A at position {}'.format(x, i+1)
    return '{} not in list A'.format(x)

x = linearSearch(A, x)
print('\n{}'.format(x))

List A:
[ 0  2  4  6  8 10 12 14 16 18 20]
Find: 9

9 not in list A


### 2.2 Jump Search
<pre>
Best case: O(1)  
Average case: O(sqrt(n))  
Worst case: O(sqrt(n))  
</pre>

In [7]:
A = np.arange(0, 21, 2)
print('List A:')
print(A)
x = random.randint(0, 20)
print('Find: {}'.format(x))

def jumpSearch(A, x):
    n = int(np.sqrt(len(A)))
    for i in range(0, len(A), n):
        if(A[i] == x):
            return 'Found {} in list A at position {}'.format(x, i+1)
        elif(A[i] > x):
            i -= n
            break
        elif(i >= len(A)):
            return '{} not in list A'.format(x)
    
    for j in range(i, i+n):
        if(A[j] == x):
            return 'Found {} in list A at position {}'.format(x, j+1)
    return '{} not in list A'.format(x)

x = jumpSearch(A, x)
print('\n{}'.format(x))

List A:
[ 0  2  4  6  8 10 12 14 16 18 20]
Find: 16

Found 16 in list A at position 9


### 2.3 Binary Search
<pre>
Best case: O(1)  
Average case: O(log(n))  
Worst case: O(log(n))  
</pre>

In [8]:
A = np.arange(0, 21, 2)
print('List A:')
print(A)
x = random.randint(0, 20)
print('Find: {}'.format(x))

def binarySearch(A, x):
    left, right = 0, len(A)-1
    while(left < right):
        middle = int((left + right)/2)
        if(A[middle] == x):
            return 'Found {} in list A at position {}'.format(x, middle+1)
        elif(A[middle] < x):
            left = middle + 1 
        else:
            right = middle - 1
    return '{} not in list A'.format(x)

x = binarySearch(A, x)
print('\n{}'.format(x))

List A:
[ 0  2  4  6  8 10 12 14 16 18 20]
Find: 6

Found 6 in list A at position 4
